=== Shooterah/ProjetDocStruct/dataCV.dtd
<!ELEMENT CVS (CV+)>
<!ELEMENT personnes (personne+)>
<!ELEMENT personne (nom, prenom, telephone)>
<!ELEMENT CV (personne, mail, linkedin, github, competances, formations)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT linkedin (#PCDATA)>
<!ELEMENT github (#PCDATA)>
<!ELEMENT competances (competance*)>
<!ELEMENT competance (#PCDATA)>
<!ELEMENT formations (formation*)>
<!ELEMENT formation (#PCDATA)>

=== Shooterah/ProjetDocStruct/Message_Reponse_XML.xml
<!-- XML qui simule une requête de toutes les infos des CV en fonction d'une competence -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CV SYSTEM "dataCV.dtd">
<CVS>
    <competence>...</competence>
</CVS>

<!-- Exemple de réponse : -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CV SYSTEM "dataCV.dtd">
<CVS>
    <CV>
        <personne>
            <nom>...</nom>
            <prenom>...</prenom>
            <telephone>...</telephone>
        </personne>
        <mail>...</mail>
        <linkedin>...</linkedin>
        <github>...</github>
        <competences>
            <competence>...</competence>
            <competence>...</competence>
            <competence>...</competence>
            <competence>...</competence>
        </competences>
        <formations>
            <formation>...</formation>
            <formation>...</formation>
            <formation>...</formation>
            <formation>...</formation>
        </formations>
    </CV>
    <CV>
        ...
    </CV>
    ...
</CVS>



<!-- XML qui simule une requête de toutes personnes en fonction d'une formation -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CV SYSTEM "dataCV.dtd">
<personne>
    <formation>...</formation>
</personne>

<!-- Exemple de réponse : -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CV SYSTEM "dataCV.dtd">
<personnes>
    <personne>
        <nom>...</nom>
        <prenom>...</prenom>
        <telephone>...</telephone>
    </personne>
    <personne>
        ...
    </personne>
    ...
</personnes>
