=== Shooterah/ProjetDocStruct/Questions/questions.dtd
<!ELEMENT question (envoyeur, (competences | formations))>
<!ATTLIST question type (CompFromCv | PersFromForma) #REQUIRED>
<!ELEMENT envoyeur (id, auteur, date)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT competences (competence*)>
<!ELEMENT competence (#PCDATA)>
<!ELEMENT formations (formation*)>
<!ELEMENT formation (#PCDATA)>

=== Shooterah/ProjetDocStruct/Questions/questions.xml
<!-- XML qui simule une requête de toutes les infos des CV en fonction d'une competence -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE question SYSTEM "questions.dtd">
<question type="CompFromCv">
    <envoyeur>
        <id>1</id>
        <auteur>...</auteur>
        <date>...</date>
    </envoyeur>
    <competences>
        <competence>...</competence>
        <competence>...</competence>
    </competences>
</question>

<!-- XML qui simule une requête de toutes personnes en fonction d'une formation -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE question SYSTEM "questions.dtd">
<question type="PersFromForma">
    <envoyeur>
        <id>2</id>
        <auteur>...</auteur>
        <date>...</date>
    </envoyeur>
    <formations>
        <formation>...</formation>
        <formation>...</formation>
    </formations>
</question>

=== Shooterah/ProjetDocStruct/ExempleQuestions/questions.xml
<!-- XML qui simule une requête de toutes les infos des CV en fonction d'une competence -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE question SYSTEM "questions.dtd">
<question typeQuestion="CompFromCv">
    <envoyeur>
        <id>1</id>
        <auteur>magalie</auteur>
        <date>19/10/2022</date>
    </envoyeur>
    <competences>
        <competence>Java</competence>
        <competence>C</competence>
    </competences>
</question>

<!-- XML qui simule une requête de toutes personnes en fonction d'une formation -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE question SYSTEM "questions.dtd">
<question typeQuestion="PersFromForma">
    <envoyeur>
        <id>2</id>
        <auteur>lorainne</auteur>
        <date>19/10/2004</date>
    </envoyeur>
    <formations>
        <formation>Ecole de la vie</formation>
    </formations>
</question>
